import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const clientHtml = await readFile(resolve(here, 'client.html'), 'utf8')
const serviceWorker = await readFile(resolve(here, 'sw.js'), 'utf8')

const manifest = {
  name: 'Hone',
  short_name: 'Hone',
  description: 'Mobile client for Hone AI gateway',
  start_url: '/',
  display: 'standalone',
  orientation: 'portrait',
  theme_color: '#0C0E12',
  background_color: '#0C0E12',
}

const output = [
  '// Generated by relay/build-assets.mjs. Do not edit by hand.',
  'export const CLIENT_HTML = ' + JSON.stringify(clientHtml) + ';',
  'export const ASSETS = {',
  "  '/sw.js': { type: 'application/javascript;charset=utf-8', body: " + JSON.stringify(serviceWorker) + ' },',
  "  '/manifest.json': { type: 'application/json;charset=utf-8', body: " + JSON.stringify(JSON.stringify(manifest)) + ' },',
  '};',
  '',
].join('\n')

await writeFile(resolve(here, 'generated-assets.js'), output, 'utf8')
